services:
  bot:
    build: .
    container_name: tg-bot
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: tg-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tg_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tg-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  celery_worker:
    build: .
    container_name: tg-celery-worker
    env_file:
      - .env
    command: celery -A bot.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: tg-celery-beat
    env_file:
      - .env
    command: celery -A bot.celery_app beat --loglevel=info --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./celerybeat:/app/celerybeat
    working_dir: /app
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
